name: Build, Publish, and Deploy Docker Image via ChatGPT

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: polarisroute/cicd-test-app:latest
          push: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Image to EC2
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_IMAGE: polarisroute/cicd-test-app:latest
        run: |
          echo "$SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $USERNAME@$HOST << EOF
            docker pull $DOCKER_IMAGE
            docker ps -q | xargs -r docker stop
            docker rm cicd-test-app || true
            docker run -d --name cicd-test-app -p 80:80 $DOCKER_IMAGE
          EOF
